// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq4ARfwCF2E00BIp3uETAdbE3FXpenGpE',
    appId: '1:625087184757:web:cb03177c97770b44851d3c',
    messagingSenderId: '625087184757',
    projectId: 'borotokar-5013d',
    authDomain: 'borotokar-5013d.firebaseapp.com',
    storageBucket: 'borotokar-5013d.firebasestorage.app',
    measurementId: 'G-XP2HH0KFD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChTt21ErmLYegEoEd4vg0WRzGWcE3hxoo',
    appId: '1:625087184757:android:40c6b2bcb1b297b5851d3c',
    messagingSenderId: '625087184757',
    projectId: 'borotokar-5013d',
    storageBucket: 'borotokar-5013d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwpra4gWZdmjvfKzYlllwGpdtlYySdBAQ',
    appId: '1:625087184757:ios:3d5c09b7a774f2af851d3c',
    messagingSenderId: '625087184757',
    projectId: 'borotokar-5013d',
    storageBucket: 'borotokar-5013d.firebasestorage.app',
    iosBundleId: 'com.example.borotokar',
  );
}
